### ISSUE TITLE
Refactor and possible bugs on 2phase-filtration.jl

### ISSUE THREAD

**Issue by stepanzh** [sofiabelen/Ideal-Gas-Compressible-Fluid#1]
@sofiabelen @vvpisarev

# Equation of state

```julia
function tait(P::AbstractFloat)
    B = 35e6
    P₀ = 1e5
    C = 0.2105
    ρ₀ = 616.18
    return ρ₀ / (1 - C * log10((B + P) / (B + P₀)))
end
```

Лучше использовать такую практику

```julia
struct TaitEoS{T}
    B::T
    P₀::T
    C::T
    ρ₀::T
end

density(x::TaitEoS, p) = x.ρ₀ / (1 - x.C * log10((x.B + x.P) / (x.B + x.P₀)))

tait_C₅H₁₂ = TaitEoS(35e6, 1e5, 0.2105, 616.18)
ρ = density(tait_C₅H₁₂, pressure)
```

Преимущества

- не придётся лезть в объявление функции, чтобы поменять вещество
- для разных уравнений состояния (Tait, Ван-дер-Ваальс, идеальный газ) создаётся унифицированный интерфейс

Аналогично для `idealgas`.

# Seems like bug

lines 244:257
```julia
f1(s) = s^2        # s is saturation of gas
f2(s) = (1 - s)^2  # s is saturation of GAS again!
f = [f1, f2]


for k = 1 : 2
    @views darcy!(f=f[k], unext=unext[k, :, :],
           vnext=vnext[k, :, :], Pnext=Pnext,
           s=(k == 1 ? snext : snext.-1), K=K,  # ternary seems incorrect: snext .- 1 is negative value
           μ=μ[k], Δx=Δx, Δy=Δy)


    @views boundaryVelocity!(f=f[k], K=K, μ=μ[k],
        s=(k == 1 ? snext : snext.-1),
        u=unext[k, :, :], v=vnext[k, :, :], P=Pnext)
end
```

Посмотри на разницу

```julia
# comment
fgas(sgas) = sgas^2
fliq(sgas) = (1 - sgas)^2  # (!)
# or define fliq as
fliq(sliq) = sliq^2  # because sgas = 1 - sliq
```

## Seems like typo

line 351

```diff
--- μ = [1.8e-5, 2,14e-4]
+++ μ = [1.8e-5, 2.14e-4]
```

# Binary search

- line 33

```diff
--- mid = left + (right - left) / 2
+++ mid = (left + right) / 2
```

- странное условие выхода line 35. А что, если `f(x) = x^2 => mid = 0`? 

```julia
if abs((right - left) / mid) < eps
```

что имеется ввиду под `eps`? Обычно это `eps_x` и тогда условие выхода

```julia
if abs(right - left) < eps
```

означает, что найденный корень локализован с точностью до `mid ⨦ eps`

также можно сделать другое условие (или ещё одно): на размер `f(mid)`.

- line 45. Лучше выбросить ошибку, означающую, что корень не был найден, тогда и line 31 не понадобится

# Misc

- есть стандартный alias для матриц

```diff
--- AbstractArray{T, 2}
+++ AbstractMatrix{T}
```

- много магических чисел: `coeff = 8.314 * 298 / 0.029`

- На моём опыте, лучше задавать количество узлов, и из него доставать `dx, dy, dt`. Возможны ошибки +-1. См. lines 333-342.

```diff
--- Δx = 0.05
--- Δy = Δx
--- nx = round(Int64, 2 / Δx)
--- ny = round(Int64, 2 / Δy)
+++ L = 2          # primary parameter
+++ nx = ny = 40  # primary parameter
+++ Δx = Δy = L / nx  # secondary parameter
```

**Comment by sofiabelen** [comment]
Пока пытаюсь разбираться с первым замечанием. Возникают ошибки типа:

`ERROR: LoadError: MethodError: no method matching length(::TaitEoS{Float64})
`

`ERROR: LoadError: MethodError: no method matching iterate(::TaitEoS{Float64})
`

От них можно избавиться если явно задавать эти методы: (хотя с iterate не понятно как написать метод)

`Base.length(x::TaitEoS) = 1
`

Эти методы требуются когда мы делаем broadcast, например:

`    @. @views ρ[2, :, 1]  = density(tait_C₅H₁₂, P[:, 1])
`

Но, вопрос такой, есть более красивый способ с этим справиться или все таки нужно так сделать?

**Comment by stepanzh** [comment]
> Но, вопрос такой, есть более красивый способ с этим справиться или все таки нужно так сделать?

https://discourse.julialang.org/t/how-to-broadcast-over-only-certain-function-arguments/19274
https://stackoverflow.com/questions/47346301/avoid-broadcasting-on-an-argument-in-julia

По всей видимости, решение такое

```julia
struct TaitEoS{T}
    B::T
    P₀::T
    C::T
    ρ₀::T
end
density(x::TaitEoS, P) = x.ρ₀ / (1 - x.C * log10((x.B + P) / (x.B + x.P₀)))

#####
##### main
#####
tait_C₅H₁₂ = TaitEoS(35e6, 1e5, 0.2105, 616.18)
P = [ 
      1e5 1e5 ;
      2e5 1e5 ;
      3e5 1e5
    ]
ρ = fill(NaN, size(P))
println(ρ)

# https://discourse.julialang.org/t/how-to-broadcast-over-only-certain-function-arguments/19274
# https://stackoverflow.com/questions/47346301/avoid-broadcasting-on-an-argument-in-julia
ρ[:, 1] .= density.(Ref(tait_C₅H₁₂), @view P[:, 1])  # Note Ref()
println(ρ)

# usage of @views macro
# @views ρ[:, 1] .= density.(Ref(tait_C₅H₁₂), P[:, 1])
# println(ρ)

# this doesn't work, the same error as in your example (broadcasting over Ref(tait_C₅H₁₂) [?])
# @. @views ρ[:, 1] = density(Ref(tait_C₅H₁₂), P[:, 1])
# println(ρ)

# broadcast on whole matrix
# ρ .= density.(Ref(tait_C₅H₁₂), P)
# println(ρ)
```

Ещё бы @vvpisarev спросить об этом.

**Comment by vvpisarev** [comment]
Судя по всему, можно добавить
```julia
Broadcast.broadcastable(eos::TaitEoS) = Ref(eos)

Broadcast.BroadcastStyle(::Type{<:TaitEoS}) = Broadcast.DefaultArrayStyle{0}()
```
Тогда всё будет автоматически оборачиваться в `Ref`.
